# Generated by Django 6.0.1 on 2026-02-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-created_at'], 'verbose_name': '3D Модель', 'verbose_name_plural': '3D Модели'},
        ),
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Превью'),
        ),
    ]
